### ISSUE TITLE
attributes static accessor

### ISSUE THREAD

**Issue by taavo** [danfinnie/superstructure#1]
We'd love to be able to ask a ValueObj class what fields are defined. Our specific use case is creating a new ValueObj class which has all the fields of another one, plus one or two, but I imagine this could be useful for other purposes as well.

Currently our best (and terrible) solution is:

`SomeValueObject.instance_methods - Object.methods - [:to_hash]`

We'd make a pull request, but... you know.

cc: @evanwang22

**Comment by danfinnie** [comment]
@taavo We added this to support your use case, please bump your gems and let us know if it works for you.

[Sample in the specs](https://github.com/danfinnie/superstructure/commit/67b1fd14dae0ccadb95f4a5c2ab2d9e7e0aef6ee#diff-c1b40d59094550ef61034df437f03a5cR176)

@MarkyMarkMcDonald and I paired on it 😱
